/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class hopper2d_lcmt implements lcm.lcm.LCMEncodable
{
    public float torso_pos[];
    public float link0_pos[];
    public float link1_pos[];
    public float link2_pos[];
 
    public hopper2d_lcmt()
    {
        torso_pos = new float[3];
        link0_pos = new float[3];
        link1_pos = new float[3];
        link2_pos = new float[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x66d7a1ad86104ea5L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.hopper2d_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.hopper2d_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.torso_pos[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.link0_pos[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.link1_pos[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.link2_pos[a]); 
        }
 
    }
 
    public hopper2d_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public hopper2d_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.hopper2d_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.hopper2d_lcmt o = new lcmtypes.hopper2d_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.torso_pos = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.torso_pos[a] = ins.readFloat();
        }
 
        this.link0_pos = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.link0_pos[a] = ins.readFloat();
        }
 
        this.link1_pos = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.link1_pos[a] = ins.readFloat();
        }
 
        this.link2_pos = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.link2_pos[a] = ins.readFloat();
        }
 
    }
 
    public lcmtypes.hopper2d_lcmt copy()
    {
        lcmtypes.hopper2d_lcmt outobj = new lcmtypes.hopper2d_lcmt();
        outobj.torso_pos = new float[(int) 3];
        System.arraycopy(this.torso_pos, 0, outobj.torso_pos, 0, 3); 
        outobj.link0_pos = new float[(int) 3];
        System.arraycopy(this.link0_pos, 0, outobj.link0_pos, 0, 3); 
        outobj.link1_pos = new float[(int) 3];
        System.arraycopy(this.link1_pos, 0, outobj.link1_pos, 0, 3); 
        outobj.link2_pos = new float[(int) 3];
        System.arraycopy(this.link2_pos, 0, outobj.link2_pos, 0, 3); 
        return outobj;
    }
 
}

