/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class loco2dOpti_lcmt implements lcm.lcm.LCMEncodable
{
    public double body_pos[];
    public double theta;
    public double r_under_contact;
    public double r_contact_pos;
    public double l_under_contact;
    public double l_contact_pos;
 
    public loco2dOpti_lcmt()
    {
        body_pos = new double[2];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xef81033a5293f20eL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.loco2dOpti_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.loco2dOpti_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 2; a++) {
            outs.writeDouble(this.body_pos[a]); 
        }
 
        outs.writeDouble(this.theta); 
 
        outs.writeDouble(this.r_under_contact); 
 
        outs.writeDouble(this.r_contact_pos); 
 
        outs.writeDouble(this.l_under_contact); 
 
        outs.writeDouble(this.l_contact_pos); 
 
    }
 
    public loco2dOpti_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public loco2dOpti_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.loco2dOpti_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.loco2dOpti_lcmt o = new lcmtypes.loco2dOpti_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.body_pos = new double[(int) 2];
        for (int a = 0; a < 2; a++) {
            this.body_pos[a] = ins.readDouble();
        }
 
        this.theta = ins.readDouble();
 
        this.r_under_contact = ins.readDouble();
 
        this.r_contact_pos = ins.readDouble();
 
        this.l_under_contact = ins.readDouble();
 
        this.l_contact_pos = ins.readDouble();
 
    }
 
    public lcmtypes.loco2dOpti_lcmt copy()
    {
        lcmtypes.loco2dOpti_lcmt outobj = new lcmtypes.loco2dOpti_lcmt();
        outobj.body_pos = new double[(int) 2];
        System.arraycopy(this.body_pos, 0, outobj.body_pos, 0, 2); 
        outobj.theta = this.theta;
 
        outobj.r_under_contact = this.r_under_contact;
 
        outobj.r_contact_pos = this.r_contact_pos;
 
        outobj.l_under_contact = this.l_under_contact;
 
        outobj.l_contact_pos = this.l_contact_pos;
 
        return outobj;
    }
 
}

