/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class terrain_lcmt implements lcm.lcm.LCMEncodable
{
    public double floor[];
 
    public terrain_lcmt()
    {
        floor = new double[1500];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x73b4665c25b9a6c6L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.terrain_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.terrain_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 1500; a++) {
            outs.writeDouble(this.floor[a]); 
        }
 
    }
 
    public terrain_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public terrain_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.terrain_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.terrain_lcmt o = new lcmtypes.terrain_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.floor = new double[(int) 1500];
        for (int a = 0; a < 1500; a++) {
            this.floor[a] = ins.readDouble();
        }
 
    }
 
    public lcmtypes.terrain_lcmt copy()
    {
        lcmtypes.terrain_lcmt outobj = new lcmtypes.terrain_lcmt();
        outobj.floor = new double[(int) 1500];
        System.arraycopy(this.floor, 0, outobj.floor, 0, 1500); 
        return outobj;
    }
 
}

