/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) position_contact_points_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s1[21] = {17, 1, 0, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};
static const casadi_int casadi_s2[39] = {3, 9, 0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2};

/* position_contact_points:(i0[12],i1[17])->(o0[3x9]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][0] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a1=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][1]=a1;
  a2=0.;
  if (res[0]!=0) res[0][2]=a2;
  a3=arg[1]? arg[1][11] : 0;
  a4=arg[0]? arg[0][2] : 0;
  a5=arg[0]? arg[0][3] : 0;
  a6=(a4+a5);
  a6=sin(a6);
  a6=(a3*a6);
  a6=(a0+a6);
  if (res[0]!=0) res[0][3]=a6;
  a7=(a4+a5);
  a7=cos(a7);
  a3=(a3*a7);
  a3=(a1-a3);
  if (res[0]!=0) res[0][4]=a3;
  if (res[0]!=0) res[0][5]=a2;
  a7=arg[1]? arg[1][12] : 0;
  a8=(a4+a5);
  a9=arg[0]? arg[0][4] : 0;
  a8=(a8+a9);
  a8=sin(a8);
  a8=(a7*a8);
  a6=(a6+a8);
  a8=arg[1]? arg[1][14] : 0;
  a10=(a4+a5);
  a10=(a10+a9);
  a11=arg[0]? arg[0][5] : 0;
  a10=(a10+a11);
  a12=1.5707963267948966e+00;
  a10=(a10+a12);
  a10=sin(a10);
  a13=(a8*a10);
  a13=(a6-a13);
  if (res[0]!=0) res[0][6]=a13;
  a13=(a4+a5);
  a13=(a13+a9);
  a13=cos(a13);
  a7=(a7*a13);
  a3=(a3-a7);
  a7=(a4+a5);
  a7=(a7+a9);
  a7=(a7+a11);
  a7=(a7+a12);
  a7=cos(a7);
  a8=(a8*a7);
  a8=(a3+a8);
  if (res[0]!=0) res[0][7]=a8;
  a5=(a4+a5);
  a5=(a5+a9);
  a5=(a5+a11);
  a5=(a5+a12);
  if (res[0]!=0) res[0][8]=a5;
  if (res[0]!=0) res[0][9]=a6;
  if (res[0]!=0) res[0][10]=a3;
  if (res[0]!=0) res[0][11]=a5;
  a12=arg[1]? arg[1][13] : 0;
  a10=(a12*a10);
  a6=(a6+a10);
  if (res[0]!=0) res[0][12]=a6;
  a12=(a12*a7);
  a3=(a3-a12);
  if (res[0]!=0) res[0][13]=a3;
  if (res[0]!=0) res[0][14]=a5;
  a5=arg[1]? arg[1][16] : 0;
  a3=sin(a4);
  a12=(a5*a3);
  a12=(a0-a12);
  a7=2.;
  a6=(a5/a7);
  a10=cos(a4);
  a11=(a6*a10);
  a12=(a12-a11);
  if (res[0]!=0) res[0][15]=a12;
  a12=cos(a4);
  a11=(a5*a12);
  a11=(a1+a11);
  a4=sin(a4);
  a6=(a6*a4);
  a11=(a11-a6);
  if (res[0]!=0) res[0][16]=a11;
  if (res[0]!=0) res[0][17]=a2;
  a3=(a5*a3);
  a3=(a0-a3);
  a11=(a5/a7);
  a6=(a11*a10);
  a3=(a3+a6);
  if (res[0]!=0) res[0][18]=a3;
  a12=(a5*a12);
  a12=(a1+a12);
  a11=(a11*a4);
  a12=(a12+a11);
  if (res[0]!=0) res[0][19]=a12;
  if (res[0]!=0) res[0][20]=a2;
  a12=(a5/a7);
  a11=(a12*a10);
  a11=(a0+a11);
  if (res[0]!=0) res[0][21]=a11;
  a12=(a12*a4);
  a12=(a1+a12);
  if (res[0]!=0) res[0][22]=a12;
  if (res[0]!=0) res[0][23]=a2;
  a5=(a5/a7);
  a10=(a5*a10);
  a0=(a0-a10);
  if (res[0]!=0) res[0][24]=a0;
  a5=(a5*a4);
  a1=(a1-a5);
  if (res[0]!=0) res[0][25]=a1;
  if (res[0]!=0) res[0][26]=a2;
  return 0;
}

CASADI_SYMBOL_EXPORT int position_contact_points(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int position_contact_points_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int position_contact_points_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void position_contact_points_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int position_contact_points_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void position_contact_points_release(int mem) {
}

CASADI_SYMBOL_EXPORT void position_contact_points_incref(void) {
}

CASADI_SYMBOL_EXPORT void position_contact_points_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int position_contact_points_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int position_contact_points_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real position_contact_points_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* position_contact_points_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* position_contact_points_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* position_contact_points_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* position_contact_points_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int position_contact_points_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
