/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace LCMTypes
{
    public sealed class hopper2dOpti_lcmt : LCM.LCM.LCMEncodable
    {
        public double[] body_pos;
        public double theta;
        public double under_contact;
        public double contact_pos;
 
        public hopper2dOpti_lcmt()
        {
            body_pos = new double[2];
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x49474f0536e92fb3L;
 
        static hopper2dOpti_lcmt()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("LCMTypes.hopper2dOpti_lcmt"))
                return 0L;
 
            classes.Add("LCMTypes.hopper2dOpti_lcmt");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            for (int a = 0; a < 2; a++) {
                outs.Write(this.body_pos[a]); 
            }
 
            outs.Write(this.theta); 
 
            outs.Write(this.under_contact); 
 
            outs.Write(this.contact_pos); 
 
        }
 
        public hopper2dOpti_lcmt(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public hopper2dOpti_lcmt(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static LCMTypes.hopper2dOpti_lcmt _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            LCMTypes.hopper2dOpti_lcmt o = new LCMTypes.hopper2dOpti_lcmt();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.body_pos = new double[(int) 2];
            for (int a = 0; a < 2; a++) {
                this.body_pos[a] = ins.ReadDouble();
            }
 
            this.theta = ins.ReadDouble();
 
            this.under_contact = ins.ReadDouble();
 
            this.contact_pos = ins.ReadDouble();
 
        }
 
        public LCMTypes.hopper2dOpti_lcmt Copy()
        {
            LCMTypes.hopper2dOpti_lcmt outobj = new LCMTypes.hopper2dOpti_lcmt();
            outobj.body_pos = new double[(int) 2];
            for (int a = 0; a < 2; a++) {
                outobj.body_pos[a] = this.body_pos[a];
            }
 
            outobj.theta = this.theta;
 
            outobj.under_contact = this.under_contact;
 
            outobj.contact_pos = this.contact_pos;
 
            return outobj;
        }
    }
}

