/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace LCMTypes
{
    public sealed class hopper2d_lcmt : LCM.LCM.LCMEncodable
    {
        public float[] torso_pos;
        public float[] link0_pos;
        public float[] link1_pos;
        public float[] link2_pos;
 
        public hopper2d_lcmt()
        {
            torso_pos = new float[3];
            link0_pos = new float[3];
            link1_pos = new float[3];
            link2_pos = new float[3];
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x66d7a1ad86104ea5L;
 
        static hopper2d_lcmt()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("LCMTypes.hopper2d_lcmt"))
                return 0L;
 
            classes.Add("LCMTypes.hopper2d_lcmt");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            for (int a = 0; a < 3; a++) {
                outs.Write(this.torso_pos[a]); 
            }
 
            for (int a = 0; a < 3; a++) {
                outs.Write(this.link0_pos[a]); 
            }
 
            for (int a = 0; a < 3; a++) {
                outs.Write(this.link1_pos[a]); 
            }
 
            for (int a = 0; a < 3; a++) {
                outs.Write(this.link2_pos[a]); 
            }
 
        }
 
        public hopper2d_lcmt(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public hopper2d_lcmt(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static LCMTypes.hopper2d_lcmt _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            LCMTypes.hopper2d_lcmt o = new LCMTypes.hopper2d_lcmt();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.torso_pos = new float[(int) 3];
            for (int a = 0; a < 3; a++) {
                this.torso_pos[a] = ins.ReadSingle();
            }
 
            this.link0_pos = new float[(int) 3];
            for (int a = 0; a < 3; a++) {
                this.link0_pos[a] = ins.ReadSingle();
            }
 
            this.link1_pos = new float[(int) 3];
            for (int a = 0; a < 3; a++) {
                this.link1_pos[a] = ins.ReadSingle();
            }
 
            this.link2_pos = new float[(int) 3];
            for (int a = 0; a < 3; a++) {
                this.link2_pos[a] = ins.ReadSingle();
            }
 
        }
 
        public LCMTypes.hopper2d_lcmt Copy()
        {
            LCMTypes.hopper2d_lcmt outobj = new LCMTypes.hopper2d_lcmt();
            outobj.torso_pos = new float[(int) 3];
            for (int a = 0; a < 3; a++) {
                outobj.torso_pos[a] = this.torso_pos[a];
            }
 
            outobj.link0_pos = new float[(int) 3];
            for (int a = 0; a < 3; a++) {
                outobj.link0_pos[a] = this.link0_pos[a];
            }
 
            outobj.link1_pos = new float[(int) 3];
            for (int a = 0; a < 3; a++) {
                outobj.link1_pos[a] = this.link1_pos[a];
            }
 
            outobj.link2_pos = new float[(int) 3];
            for (int a = 0; a < 3; a++) {
                outobj.link2_pos[a] = this.link2_pos[a];
            }
 
            return outobj;
        }
    }
}

