/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace LCMTypes
{
    public sealed class terrain_lcmt : LCM.LCM.LCMEncodable
    {
        public double[] floor;
 
        public terrain_lcmt()
        {
            floor = new double[1000];
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x73b4665c25b4a6c6L;
 
        static terrain_lcmt()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("LCMTypes.terrain_lcmt"))
                return 0L;
 
            classes.Add("LCMTypes.terrain_lcmt");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            for (int a = 0; a < 1000; a++) {
                outs.Write(this.floor[a]); 
            }
 
        }
 
        public terrain_lcmt(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public terrain_lcmt(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static LCMTypes.terrain_lcmt _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            LCMTypes.terrain_lcmt o = new LCMTypes.terrain_lcmt();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.floor = new double[(int) 1000];
            for (int a = 0; a < 1000; a++) {
                this.floor[a] = ins.ReadDouble();
            }
 
        }
 
        public LCMTypes.terrain_lcmt Copy()
        {
            LCMTypes.terrain_lcmt outobj = new LCMTypes.terrain_lcmt();
            outobj.floor = new double[(int) 1000];
            for (int a = 0; a < 1000; a++) {
                outobj.floor[a] = this.floor[a];
            }
 
            return outobj;
        }
    }
}

