//
// Academic License - for use in teaching, academic research, and meeting
// course requirements at degree granting institutions only.  Not for
// government, commercial, or other organizational use.
//
// jacobian_k.cpp
//
// Code generation for function 'jacobian_k'
//

// Include files
#include "jacobian_k.h"
#include <cmath>
#include <cstring>

// Function Definitions
void jacobian_k(const double in1[12], const double in2[17], double J_k[18])
{
  double t5;
  double t6;
  // JACOBIAN_K
  //     J_k = JACOBIAN_K(IN1,IN2)
  //     This function was generated by the Symbolic Math Toolbox version 9.1.
  //     25-Sep-2022 00:50:44
  t5 = in2[16] * std::sin(in1[2]) / 2.0;
  t6 = -(in2[16] * std::cos(in1[2]) / 2.0);
  J_k[0] = 1.0;
  J_k[1] = 0.0;
  J_k[2] = 0.0;
  J_k[3] = 0.0;
  J_k[4] = 1.0;
  J_k[5] = 0.0;
  J_k[6] = t5 + t6;
  J_k[7] = -t5 + t6;
  std::memset(&J_k[8], 0, 10U * sizeof(double));
}

// End of code generation (jacobian_k.cpp)
