//
// Academic License - for use in teaching, academic research, and meeting
// course requirements at degree granting institutions only.  Not for
// government, commercial, or other organizational use.
//
// jacobian_i.cpp
//
// Code generation for function 'jacobian_i'
//

// Include files
#include "jacobian_i.h"
#include <cmath>
#include <cstring>

// Function Definitions
void jacobian_i(const double in1[12], const double in2[17], double J_i[18])
{
  double t4;
  double t5;
  // JACOBIAN_I
  //     J_i = JACOBIAN_I(IN1,IN2)
  //     This function was generated by the Symbolic Math Toolbox version 9.1.
  //     25-Sep-2022 00:50:45
  t4 = in2[16] * std::cos(in1[2]) / 2.0;
  t5 = in2[16] * std::sin(in1[2]) / 2.0;
  J_i[0] = 1.0;
  J_i[1] = 0.0;
  J_i[2] = 0.0;
  J_i[3] = 0.0;
  J_i[4] = 1.0;
  J_i[5] = 0.0;
  J_i[6] = t4 - t5;
  J_i[7] = t4 + t5;
  std::memset(&J_i[8], 0, 10U * sizeof(double));
}

// End of code generation (jacobian_i.cpp)
