//
// Academic License - for use in teaching, academic research, and meeting
// course requirements at degree granting institutions only.  Not for
// government, commercial, or other organizational use.
//
// jacobian_o.cpp
//
// Code generation for function 'jacobian_o'
//

// Include files
#include "jacobian_rbody.h"

// Function Definitions
void jacobian_rbody(const double[12], const double[17], double J_body[18])
{
  static const signed char iv[18]{1, 0, 0, 0, 1, 0, 0, 0, 0,
                                  0, 0, 0, 0, 0, 0, 0, 0, 0};
  for (int i{0}; i < 18; i++) {
    J_body[i] = iv[i];
  }
  // JACOBIAN_O
  //     J_body = JACOBIAN_O(IN1,IN2)
  //     This function was generated by the Symbolic Math Toolbox version 9.1.
  //     25-Sep-2022 00:50:44
}

// End of code generation (jacobian_o.cpp)
