//
// Academic License - for use in teaching, academic research, and meeting
// course requirements at degree granting institutions only.  Not for
// government, commercial, or other organizational use.
//
// jacobian_h.cpp
//
// Code generation for function 'jacobian_h'
//

// Include files
#include "jacobian_h.h"
#include <cmath>
#include <cstring>

// Function Definitions
void jacobian_h(const double in1[12], const double in2[17], double J_h[18])
{
  double t4;
  double t5;
  // JACOBIAN_H
  //     J_h = JACOBIAN_H(IN1,IN2)
  //     This function was generated by the Symbolic Math Toolbox version 9.1.
  //     25-Sep-2022 00:50:45
  t4 = in2[16] * std::cos(in1[2]) / 2.0;
  t5 = in2[16] * std::sin(in1[2]) / 2.0;
  J_h[0] = 1.0;
  J_h[1] = 0.0;
  J_h[2] = 0.0;
  J_h[3] = 0.0;
  J_h[4] = 1.0;
  J_h[5] = 0.0;
  J_h[6] = t4 + t5;
  J_h[7] = -t4 + t5;
  std::memset(&J_h[8], 0, 10U * sizeof(double));
}

// End of code generation (jacobian_h.cpp)
