#include "jacobian_a.h"
#include "jacobian_b.h"
#include "jacobian_c.h"
#include "jacobian_e.h"
#include "jacobian_h.h"
#include "jacobian_i.h"
#include "jacobian_j.h"
#include "jacobian_k.h"
#include "jacobian_rbody.h"
void jacobians(const double in1[12], const double in2[17], int i, double J_a[18]);