"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class hopper2d_lcmt(object):
    __slots__ = ["torso_pos", "link0_pos", "link1_pos", "link2_pos"]

    __typenames__ = ["float", "float", "float", "float"]

    __dimensions__ = [[3], [3], [3], [3]]

    def __init__(self):
        self.torso_pos = [ 0.0 for dim0 in range(3) ]
        self.link0_pos = [ 0.0 for dim0 in range(3) ]
        self.link1_pos = [ 0.0 for dim0 in range(3) ]
        self.link2_pos = [ 0.0 for dim0 in range(3) ]

    def encode(self):
        buf = BytesIO()
        buf.write(hopper2d_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>3f', *self.torso_pos[:3]))
        buf.write(struct.pack('>3f', *self.link0_pos[:3]))
        buf.write(struct.pack('>3f', *self.link1_pos[:3]))
        buf.write(struct.pack('>3f', *self.link2_pos[:3]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != hopper2d_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return hopper2d_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = hopper2d_lcmt()
        self.torso_pos = struct.unpack('>3f', buf.read(12))
        self.link0_pos = struct.unpack('>3f', buf.read(12))
        self.link1_pos = struct.unpack('>3f', buf.read(12))
        self.link2_pos = struct.unpack('>3f', buf.read(12))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if hopper2d_lcmt in parents: return 0
        tmphash = (0x66d7a1ad86104ea5) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if hopper2d_lcmt._packed_fingerprint is None:
            hopper2d_lcmt._packed_fingerprint = struct.pack(">Q", hopper2d_lcmt._get_hash_recursive([]))
        return hopper2d_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", hopper2d_lcmt._get_packed_fingerprint())[0]

